INSERT INTO [Avatar]
(
[ImgUrl],
[Name]
) VALUES
(
'https://image.flaticon.com/icons/svg/145/145843.svg',
'man_with_glasses_and_beard'
),
(
'https://image.flaticon.com/icons/svg/145/145847.svg',
'woman_with_brown_hair'
),
(
'https://image.flaticon.com/icons/svg/145/145848.svg',
'man_with_beard'
),
(
'https://image.flaticon.com/icons/svg/145/145842.svg',
'man_with_grey_hair_glasses_and_beard'
),
(
'https://image.flaticon.com/icons/svg/145/145849.svg',
'man_with_brown_hair'
),
(
'https://image.flaticon.com/icons/svg/145/145850.svg',
'woman_with_black_bob'
),
(
'https://image.flaticon.com/icons/svg/145/145846.svg',
'man_with_black_hair_and_sunglasses'
),
(
'https://image.flaticon.com/icons/svg/145/145845.svg',
'man_with_black_hair'
),
(
'https://image.flaticon.com/icons/svg/145/145844.svg',
'woman_with_black_braids'
)
